#!/bin/bash

# Exit on any error
set -e

echo "============================================="
echo "  📦 PULSE Edge Windows Build Utility"
echo "============================================="

# 1. Check prerequisites
echo "Checking prerequisites..."
if ! command -v dotnet &> /dev/null; then
    echo "❌ Error: .NET SDK is not installed or not in PATH."
    exit 1
fi

# Detect package manager (pnpm preferred, npm fallback)
if command -v pnpm &> /dev/null; then
    PKG_MANAGER="pnpm"
    INSTALL_CMD="pnpm install"
    BUILD_CMD="pnpm run build"
elif command -v npm &> /dev/null; then
    PKG_MANAGER="npm"
    INSTALL_CMD="npm install"
    BUILD_CMD="npm run build"
else
    echo "❌ Error: Neither pnpm nor Node.js/npm is installed or in PATH."
    exit 1
fi

# Define Target Architecture (default to win-x86)
ARCH="win-x86"
if [ "$1" == "x64" ]; then
    ARCH="win-x64"
fi

echo "🎯 Target Architecture: $ARCH"
echo "📦 Using package manager: $PKG_MANAGER"

# Create a clean dist directory at the root
rm -rf dist
mkdir -p dist

# 2. Build the React Frontend
echo "💻 Building React UI static assets..."
cd src/Pulse.Edge.UI
$INSTALL_CMD
$BUILD_CMD
cd ../..

# 3. Copy UI static assets to Web API folder so they can be embedded
echo "📁 Copying UI static assets for embedding..."
mkdir -p src/Pulse.Edge.Api/wwwroot
rm -rf src/Pulse.Edge.Api/wwwroot/*
cp -R src/Pulse.Edge.UI/dist/ src/Pulse.Edge.Api/wwwroot/

# 4. Compile Unified API Server with Embedded UI and Self-Extracted Native DLLs
echo "🔌 Compiling Single Standalone Pulse.Edge ($ARCH) executable..."
dotnet publish src/Pulse.Edge.Api/Pulse.Edge.Api.csproj \
  -c Release \
  -r $ARCH \
  --self-contained true \
  -p:PublishSingleFile=true \
  -p:IncludeNativeLibrariesForSelfExtract=true \
  -p:PublishTrimmed=false \
  -o dist/

# Clean up web.config if it is generated by Web SDK during publish
if [ -f dist/web.config ]; then
    rm dist/web.config
fi

echo "============================================="
echo "  ✅ Build Completed Successfully!"
echo "============================================="
echo "Your single Windows executable is located at:"
echo " ➡️  dist/Pulse.Edge.exe"
echo ""
echo "This single file contains the entire application:"
echo " - React Dashboard UI (Embedded)"
echo " - Web API Server"
echo " - Background Sync & Protocols"
echo " - .NET 10.0 Runtime"
echo " - Native SQLite engines"
echo ""
echo "You only need to distribute this single 'Pulse.Edge.exe'"
echo "file to the target Windows machine!"
echo ""
echo "To compile for 64-bit Windows instead, run:"
echo "  ./build-windows.sh x64"
echo "============================================="
