<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pulse.Edge.Storage\Pulse.Edge.Storage.csproj" />
    <ProjectReference Include="..\Pulse.Edge.Agent\Pulse.Edge.Agent.csproj" />
    <ProjectReference Include="..\Pulse.Edge.Cloud\Pulse.Edge.Cloud.csproj" />
    <ProjectReference Include="..\Pulse.Edge.Protocols.MqttProtocol\Pulse.Edge.Protocols.MqttProtocol.csproj" />
    <ProjectReference Include="..\Pulse.Edge.Protocols.LibPlcTag\Pulse.Edge.Protocols.LibPlcTag.csproj" />
  </ItemGroup>

</Project>