<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Pulse.Edge</AssemblyName>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**" />
    <Content Remove="wwwroot\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pulse.Edge.Storage\Pulse.Edge.Storage.csproj" />
    <ProjectReference Include="..\Pulse.Edge.Protocols.OpcUa\Pulse.Edge.Protocols.OpcUa.csproj" />
    <ProjectReference Include="..\Pulse.Edge.Agent\Pulse.Edge.Agent.csproj" />
  </ItemGroup>

</Project>
